### PR TITLE
'addNotes' API call

### PR DESCRIPTION
**Pull request by douglasfsmn**
Creates 'addNotes' API call.  If this pull request is accepted, I will also submit code for RTM-CLI to add an 'addNotes' command.

### CODE REVIEW

**Comment by aberezin** [comment]
@douglasfsmn Can you update your PR to update the README.md to include the addNotes call

**Comment by douglasfsmn** [comment]
The addNotes() call should already be in the README.md file.  What am I missing?

**Comment by aberezin** [comment]
sorry, my mistake.  Can you commit the corresponding changes to your cli repo, https://github.com/douglasfsmn/rtm-cli ?
Ill clone that and your api repo and start adding my extensions.  thx.

**Comment by douglasfsmn** [comment]
I'll get CLI ready - it wasn't queued-up like API was. It won't take long.

-------- Original Message --------

**Comment by douglasfsmn** [comment]
Alan,

My 'dev' branches in both rtm-api and rtm-cli should be good to go. Let me know what else you need from me.

https://github.com/douglasfsmn/rtm-cli/tree/dev
https://github.com/douglasfsmn/rtm-api/tree/dev

Doug

------- Original Message -------

**Comment by beauraines** [comment]
FYI - I just submitted a PR to display the tasks notes in rtm-cli https://github.com/dwaring87/rtm-cli/pull/25

**Pull request merged**
